config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get '/login' => 'sessions#new', as: 'login'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy', as: 'logout'

  resources :films, :only => [:index, :show] do
    resources :comments, :only => [:create, :update, :destroy]
    resources :reviews, :only => [:create, :show] do
      resources :comments, :only => [:create, :update, :destroy]
      resources :ratings, :only => [:create]
    end
    resources :ratings, :only => [:create]
  end

  resources :users, :except => [:index, :destroy]

end

app/models/film.rb
# == Schema Information
#
# Table name: films
#
#  id          :integer          not null, primary key
#  title       :string
#  runtime     :string
#  genre       :string
#  year        :integer
#  director    :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Film < ActiveRecord::Base
  has_many :comments, as: :commentable
  has_many :reviews
  has_many :ratings, as: :rateable

  def average_rating
    if self.ratings.length > 0
      self.ratings.reduce(0){|sum, rating| sum + rating.value } / self.ratings.length.to_f
    else
      "unrated"
    end
  end

  def rounded_stars
    stars = (self.average_rating * 2).to_i / 2.0
    case stars
    when 1.0
    when 1.5
    when 2.0
    when 2.5
    when 3.0
    when 3.5
    when 4.0
    end
  end

  def self.top_five
    self.all.to_a.sort_by {|film| film.average_rating}.reverse[0..4]
  end

  def already_rated(user_id)
    user = User.find(user_id)
    rating_users = []
    self.ratings.to_a.each do |rating|
      rating_users << rating.rater
    end
    rating_users.include?(user)
  end

  def current_user_rating(user_id)
    user = User.find(user_id)
    rating = user.ratings.where(rateable_id: self.id, rateable_type: "Film")
    rating.first.value
  end

end

app/controllers/films_controller.rb
# == Schema Information
#
# Table name: films
#
#  id          :integer          not null, primary key
#  title       :string
#  runtime     :string
#  genre       :string
#  year        :integer
#  director    :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class FilmsController < ApplicationController
	def index
		@films = Film.all
	end

	def show
		@film = Film.find(params[:id])
  end

end

app/views/films/index.html.erb
<h1 class="page-header">Films</h1>

<% @films.each do |film| %>
	<div class="film-container">
		<div class="film-data">
			<h2 class="movie-title"><%= link_to film.title, film_path(film) %> <span class="sub-header">(<%= film.average_rating %>, <%= film.ratings.count %> ratings)</h2>
      <p class="description">Directed by <%= film.director %>, <%= film.year %>. <%= film.runtime %></p>
      <p class="description">Synopsis: <%= film.description %></p>
		</div>
	</div>
<% end %>

app/views/films/show.html.erb
<h1 class="page-header"><%= @film.title %>
		<span style="font-size: 0.5em;">(<%= @film.average_rating %> stars, <%= @film.ratings.count %> ratings)</span>
</h1>

<% if session[:user_id] && @film.already_rated(session[:user_id]) %>
	<div class="film-rating">
		<% @film.current_user_rating(session[:user_id]).times do %>
			<span class="star-static">★</span>
		<% end %>
		<% (4 - @film.current_user_rating(session[:user_id])).times do %>
			<span class="star-static">☆</span>
		<% end %>
	</div>
	<br>
<% elsif session[:user_id] %>
	<div class="film-rating">
		<span class="film-star" id="film-rating-1">☆</span><span class="film-star" id="film-rating-2">☆</span><span class="film-star" id="film-rating-3">☆</span><span class="film-star" id="film-rating-4">☆</span>
	</div>
	<br>
<% end %>

<div class="description film-data">
	<p>Directed by <%= @film.director %>, <%= @film.year %>. <%= @film.runtime %></></p>
	<p>Synopsis: <%= @film.description %></p>
</div>

<div class="reviews-container" style="border: 2px solid #eeeeee;">
	<h2 class="page-header form-label">Summary</h2>
	<div class="review-summary">
	<!--
	====== Display film average rating and review count ================
	 -->
		  <p class="description">Average Rating: <%= @film.average_rating %></p>
			<p class="description">Number of Reviews: <%= @film.reviews.count %> reviews</p>
	<!--
	====== Display review form if user is signed in ====================
	====== Else, invite user to sign in or sign up to do so ============
	 -->
		<% if session[:user_id] %>
			<%= render 'reviews/form' %>
      <!-- Comment on the film -->
      <%= render 'comments/film_form', film: @film %>
    <% else %>

      <p class="description">Want to write a review?
         <%= link_to 'Sign in', login_path %> or
         <%= link_to 'Sign up', new_user_path %>!
      </p>
    <% end %>
  </div>

  <div class="review-container">
    <h3 class="page-header">Reviews</h3>
    <%= render @film.reviews %>

<!-- Comments on the Movie -->
    <h3 class="page-header">Comments on the Movie</h3>
    <% @film.comments.each do |comment|%>
      <p class="description"><%= comment.content %></p>
      <%  if session[:user_id] == comment.commenter_id %>
      <button><%= link_to "Delete Comment", method: :delete, data: {confirm: "Are you sure you want to delete this comment?"} %></button>
      <% end %>
    <% end %>

  </div>

</div>