config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get '/login' => 'sessions#new', as: 'login'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy', as: 'logout'

  resources :films, :only => [:index, :show] do
    resources :comments, :only => [:create, :update, :destroy]
    resources :reviews, :only => [:create, :show] do
      resources :comments, :only => [:create, :update, :destroy]
      resources :ratings, :only => [:create]
    end
    resources :ratings, :only => [:create]
  end

  resources :users, :except => [:index, :destroy]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Wintergarten</title>

    <!-- Bootstrap Core CSS -->
    <%= stylesheet_link_tag "application" %>

    <!-- Custom Fonts -->
    <link href="/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

    <!-- Navigation -->
    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">
                    <!-- <i class="fa fa-play-circle"></i>  <span class="light"></span> -->
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                <ul class="nav navbar-nav">
                  <% if session[:user_id] != nil %>
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li class="page-scroll">
                      <span class="nav-link"><%= link_to 'Home', root_path %></span>
                    </li>
                    <li class="page-scroll">
                      <span class="nav-link"><%= link_to 'Profile', user_path(session[:user_id]) %></span>
                    </li>
                    <li class="page-scroll">
                      <span class="nav-link"><%= link_to 'Logout', logout_path, method: :get %></span>
                    </li>
                  <% else %>
                    <li class="page-scroll">
                      <span class="nav-link"><%= link_to 'Home', root_path %></span>
                    </li>
                    <li class="page-scroll">
                      <span class="nav-link"><%= link_to 'Login', login_path %></span>
                    </li>
                    <li class="page-scroll">
                      <span class="nav-link"><%= link_to 'Register', new_user_path %></span>
                    </li>
                  <% end %>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

<%= yield %>

<!-- Footer -->
<footer>

</footer>

<%= javascript_include_tag "application" %>

<!-- Google Maps API Key - Use your own API key to enable the map feature. More information on the Google Maps API can be found at https://developers.google.com/maps/ -->
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCRngKslUGJTlibkQ3FkfTxj3Xss1UlZDA&sensor=false"></script>

</body>
</html>